services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"